from services.services_model import Service, ServiceType

_SERVICES: list[Service] = [
    Service(
        id="sammlung_backend",
        name="Sammlung Backend",
        url="https://sammlung.app/api/health",
        type=ServiceType.health_endpoint,
        description="Sammlung app",
        github="https://github.com/marcjulianschwarz/app-support-sammlung",
        service_kind="FastAPI",
        port_range="70",
        port=8070,
        internal_port=8000,
        container_name="production-sammlung-backend-1",
    ),
    Service(
        id="sammlung_frontend",
        name="Sammlung Frontend",
        url="https://sammlung.app",
        type=ServiceType.ping,
        description="Sammlung app",
        github="https://github.com/marcjulianschwarz/app-support-sammlung",
        service_kind="Vite",
        port_range="70",
        port=8071,
        internal_port=3000,
        container_name="production-sammlung-frontend-1",
    ),
    # Content
    Service(
        id="Personal Page",
        name="marc-julian.com",
        url="https://marc-julian.com",
        type=ServiceType.ping,
        description="My main web page on the internt",
        github="https://github.com/marcjulianschwarz/marc-julian.com",
        service_kind="Static",
    ),
    Service(
        id="photography",
        name="Photography",
        url="https://shots.marc-julian.com",
        type=ServiceType.ping,
        description="Photography on shots.marc-julian.com",
        github="https://github.com/marcjulianschwarz/shots",
        service_kind="Astro",
    ),
    Service(
        id="blog",
        name="Blog",
        url="https://marc-julian.com/blog",
        type=ServiceType.ping,
        github="https://github.com/marcjulianschwarz/obsidian-vault-blog",
        service_kind="Astro",
    ),
    Service(
        id="test-blog",
        name="Test Blog",
        url="https://testblog.marc-julian.com/blog",
        type=ServiceType.ping,
        description="Test Blog",
        github="https://github.com/marcjulianschwarz/obsidian-vault-blog",
        service_kind="Astro",
    ),
    Service(
        id="notes",
        name="Notes",
        url="https://notes.marc-julian.com",
        type=ServiceType.ping,
        github="https://github.com/marcjulianschwarz/obsidian-vault-notes",
        service_kind="Quartz",
    ),
    Service(
        id="the-brew-code",
        name="The Brew Code",
        url="https://the-brew-code.de",
        type=ServiceType.ping,
        description="German wiki all about coffee",
        github="https://github.com/the-brew-code/coffee",
        service_kind="Quartz",
    ),
    Service(
        id="recipes",
        name="Recipes",
        url="https://recipes.marc-julian.com",
        type=ServiceType.ping,
        description="A collection of recipes",
        github="https://github.com/marcjulianschwarz/obsidian-vault-recipes",
        service_kind="Astro",
    ),
    Service(
        id="counter",
        name="Counter",
        url="https://counter.marc-julian.com",
        type=ServiceType.ping,
        description="Counter app inspired by Alltagszähler",
        github="https://github.com/marcjulianschwarz/counter",
        service_kind="",
    ),
    Service(
        id="wizard",
        name="Wizard Frontend",
        url="https://wizard.marc-julian.com",
        type=ServiceType.ping,
        description="Companion app for the card game Wizard",
        github="https://github.com/marcjulianschwarz/wizard",
        service_kind="Vite",
        port_range="10",
        port=8011,
        internal_port=3000,
        container_name="wizard-frontend-1",
    ),
    Service(
        id="wizard-backend",
        name="Wizard Backend",
        url="https://wizard.marc-julian.com",
        type=ServiceType.ping,
        description="Companion app for the card game Wizard",
        github="https://github.com/marcjulianschwarz/wizard",
        service_kind="Vite",
        port_range="10",
        port=8010,
        internal_port=3000,
        container_name="wizard-backend-1",
    ),
    Service(
        id="gemeindediener",
        name="Gemeindediener Frontend",
        url="https://bible.marc-julian.com",
        type=ServiceType.ping,
        description="A church management tool.",
        github="https://github.com/marcjulianschwarz/gemeindediener",
        service_kind="Vite",
        port_range="6000",
        port=6002,
        internal_port=80,
        container_name="gemeindediener-frontend",
    ),
    Service(
        id="gemeindediener-backend",
        name="Gemeindediener Backend",
        url="https://bible.marc-julian.com",
        type=ServiceType.ping,
        description="A church management tool.",
        github="https://github.com/marcjulianschwarz/gemeindediener",
        service_kind="NestJS",
        port_range="6000",
        port=6001,
        internal_port=3000,
        container_name="gemeindediener-backend",
    ),
    Service(
        id="tools",
        name="Tools",
        url="https://tools.marc-julian.com",
        type=ServiceType.ping,
        description="A collection of useful tools, mostly dev tools.",
        github="https://github.com/marcjulianschwarz/tools",
        service_kind="",
    ),
    Service(
        id="qr-code",
        name="QR Code Frontend",
        url="https://qr.marc-julian.com",
        type=ServiceType.ping,
        description="QR code redirection service",
        github="https://github.com/marcjulianschwarz/qr",
        service_kind="Vite",
        port_range="20",
        port=8021,
        internal_port=3000,
        container_name="qr-frontend-1",
    ),
    Service(
        id="qr-code-backend",
        name="QR Code Backend",
        url="https://qr.marc-julian.com",
        type=ServiceType.ping,
        description="QR code redirection service",
        github="https://github.com/marcjulianschwarz/qr",
        service_kind="FastAPI",
        port_range="20",
        port=8020,
        internal_port=3000,
        container_name="qr-backend-1",
    ),
    Service(
        id="mdsnip",
        name="MDsnip Frontend",
        url="https://mdsnip.com",
        type=ServiceType.ping,
        description="Create shareable markdown snippets",
        github="https://github.com/marcjulianschwarz/mdsnip",
        service_kind="Vite",
        port_range="30",
        port=8031,
        internal_port=3000,
        container_name="mdsnip-frontend-1",
    ),
    Service(
        id="mdsnip",
        name="MDsnip Backend",
        url="https://mdsnip.com",
        type=ServiceType.ping,
        description="Create shareable markdown snippets",
        github="https://github.com/marcjulianschwarz/mdsnip",
        service_kind="Vite",
        port_range="30",
        port=8030,
        internal_port=3000,
        container_name="mdsnip-backend-1",
    ),
    Service(
        id="lib",
        name="Lib",
        url="https://lib.marc-julian.com",
        type=ServiceType.ping,
        description="My React component library.",
        github="https://github.com/marcjulianschwarz/lib",
        service_kind="Vite",
    ),
    Service(
        id="status",
        name="Status Frontend",
        url="https://status.marc-julian.com",
        type=ServiceType.ping,
        description="This status service ;)",
        github="https://github.com/marcjulianschwarz/status",
        service_kind="Vite",
    ),
    Service(
        id="phoenix",
        name="Phoenix",
        url="https://phoenix.marc-julian.com",
        type=ServiceType.ping,
        description="Phoenix",
        service_kind="",
    ),
    Service(
        id="portainer",
        name="Portainer",
        url="https://portainer.marc-julian.com",
        type=ServiceType.ping,
        description="Portainer",
        service_kind="",
    ),
]


class ServicesRepo:
    def get_all(self) -> list[Service]:
        return sorted(_SERVICES, key=lambda s: s.name.lower())

    def get_by_id(self, service_id: str) -> Service | None:
        return next((s for s in _SERVICES if s.id == service_id), None)
